#!/usr/bin/python3
"""Spotify (through Spicetify) in the Glass look.   tools/gen_spotify.py [--apply]
Writes the Spicetify theme "Glass" (~/.config/spicetify/Themes/Glass): color.ini with a dark and a light scheme, built from
design/tokens.json and the desktop's CURRENT accent (the shell's config), plus apps/spotify/user.css. With --apply it also
selects the scheme of the current mode and asks Spicetify to refresh. Does nothing when Spicetify is not installed."""
import colorsys, json, os, shutil, subprocess, sys
R = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
T = json.load(open(os.path.join(R, "design", "tokens.json")))
try: C = json.load(open(os.path.expanduser("~/.config/sirca-shell/config.json")))
except Exception: C = {}
acc = str(C.get("accent", "#4c6ed6")).lstrip("#"); acc = acc if len(acc) == 6 else "4c6ed6"
mode = "light" if C.get("mode") == "light" else "dark"
def rgb(h): h = h.lstrip("#"); return tuple(int(h[i:i + 2], 16) / 255 for i in (0, 2, 4))
def hx(c): return "%02x%02x%02x" % tuple(round(max(0, min(1, v)) * 255) for v in c)
def mix(a, b, t): return tuple(a[i] + (b[i] - a[i]) * t for i in range(3))
def shade(h, dl, ds=0.0):
    hh, l, s = colorsys.rgb_to_hls(*rgb(h)); return hx(colorsys.hls_to_rgb(hh, max(0, min(1, l + dl)), max(0, min(1, s + ds))))
# Glass Key (KWin effect, kwin-effects-glass/glasskey): Spotify cannot paint a transparent window, so its SURFACES are painted in
# exact key colours that the effect turns into glass while text and pictures stay solid. The keys carry a small FIXED navy
# tint (never the accent: Spotify only picks a new accent up at its next start, the effect reads its settings at once), which
# keeps neutral pictures off the key line. Without the effect they are simply the theme's near-black / near-white surfaces.
# ONE key per mode. The window (chrome) is the bare key; panels are the key plus PANEL (4 %) of the text colour, which is what
# the effect's shader expects (its alpha and tint are continuous along key -> text; two separate keys drew lines across panels).
KEY = {False: "14171d", True: "f6f8fd"}; PANEL = 0.08     # must match PANEL in the Glass Key shader
def panel_of(light): return hx(mix(rgb(KEY[light]), rgb((T["light"] if light else T["dark"])["text"]), PANEL))
KEYS = {False: {"content": None, "chrome": KEY[False]}, True: {"content": None, "chrome": KEY[True]}}
def scheme(p, light):
    a = rgb(acc); w = rgb(p["window"]); txt = rgb(p["text"])
    tint = lambda h, t=0.0: hx(mix(rgb(h), a, t * 0.0))         # NEUTRAL, like the Qt and GTK apps (an accent tint read as "colours off" on the translucent window)
    button = shade(acc, -0.06) if light else acc                # on white the accent needs a little more weight
    K = {"chrome": KEY[light], "content": panel_of(light)}
    return {"text": hx(txt), "subtext": p["textDim"].lstrip("#"), "main": K["content"], "main-elevated": tint(p["card"], 0.06),
            "highlight": hx(mix(w, txt, 0.08)), "highlight-elevated": hx(mix(w, txt, 0.12)), "sidebar": K["chrome"], "player": K["chrome"],
            "card": tint(p["card"], 0.06), "shadow": "000000", "selected-row": hx(mix(txt, w, 0.25)), "button": button, "button-active": shade(button, 0.06),
            "button-disabled": hx(mix(w, txt, 0.22)), "tab-active": hx(mix(w, txt, 0.12)), "notification": tint(p["card"], 0.10), "notification-error": "d6494f", "glass-sheen": (K["content"] if light else "ffffff"), "misc": hx(mix(w, txt, 0.30))}
cfgdir = os.path.expanduser("~/.config/spicetify")
if not shutil.which("spicetify") and not os.path.isdir(cfgdir): sys.exit(0)
dst = os.path.join(cfgdir, "Themes", "Glass"); os.makedirs(dst, exist_ok=True)
out = "; generated by glass-desktop/tools/gen_spotify.py from design/tokens.json + the current accent (#%s). Do not edit.\n" % acc
for name, p, light in (("glass-dark", T["dark"], False), ("glass-light", T["light"], True)):
    out += "\n[%s]\n" % name + "".join("%-19s= %s\n" % kv for kv in scheme(p, light).items())
# Light / dark and the accent WITHOUT restarting Spotify: color.ini holds a scheme per mode, Spicetify is pointed at the
# current mode's scheme and `refresh` rewrites colors.css inside the app; the extension apps/spotify/glass-live.js (installed
# here) notices the changed file and re-links it in the running app. (Spotify's browser does not follow the system's
# colour-scheme preference, so a media query cannot do this.)
css = open(os.path.join(R, "apps", "spotify", "user.css")).read()
ext = os.path.join(cfgdir, "Extensions"); os.makedirs(ext, exist_ok=True)
shutil.copyfile(os.path.join(R, "apps", "spotify", "glass-live.js"), os.path.join(ext, "glass-live.js"))
for name, text in (("color.ini", out), ("user.css", css)):
    f = os.path.join(dst, name)
    if not os.path.isfile(f) or open(f).read() != text: tmp = f + ".tmp"; open(tmp, "w").write(text); os.replace(tmp, f)
# the effect's side of the key: colours for the CURRENT mode, the neutral glass tints and opacities from the tokens
if shutil.which("kwriteconfig6"):
    P = T["light"] if mode == "light" else T["dark"]; G = T["glass"]
    # With HDR on, the compositor shows Chromium's surfaces darker than other windows' same colours, and the glass tint goes
    # through that surface's transform. Measured against a terminal with the same glass (#18191b at 62 %, #f3f4f6 at 44 %):
    # dark needs the tint lifted by 12 of 255 (13 -> 25), light needs pure white (implied 223 -> 239, terminal 242).
    # An own encoding in the shader (gamma 2.2 x the output's reference white) was tried and is wrong at both ends
    # (dark tint came out black, mid grey too bright). "spotifyTintLift" in the shell config overrides the dark guess.
    def hdr_on():
        try:
            d = json.loads(subprocess.run(["kscreen-doctor", "-j"], capture_output=True, text=True, timeout=5).stdout)
            return any(o.get("enabled") and o.get("hdr") for o in d.get("outputs", []))
        except Exception: return False
    HDR = hdr_on()
    # 2026-09-21: NO lift by default any more. The lift (12 in dark, pure white in light) was calibrated while the shader still
    # applied its alpha to the decoration a second time and before its colour path was fixed; measured now over plain light
    # and dark backdrops, the unlifted tints give exactly the terminal's and the title bar's values in both modes.
    lift = C.get("spotifyTintLift"); lift = int(lift) if isinstance(lift, (int, float)) else 0
    def lifted(h):
        if mode == "light": return h
        return "#" + hx(tuple(min(1.0, v + lift / 255.0) for v in rgb(h)))
    vals = {"ContentKey": "#" + KEY[mode == "light"], "ChromeKey": "#" + scheme(P, mode == "light")["button"], "Text": P["text"], "ContentTint": lifted(P["view"]), "ChromeTint": lifted(P["sidebar"]),
            "ContentAlpha": G.get("contentOpacityLight" if mode == "light" else "contentOpacity", 0.72), "ChromeAlpha": 0.46 if mode == "light" else 0.62,
            "Shadow": 0.22 if mode == "light" else 0.30}      # own shadow of undecorated windows (the Miniplayer); needs the glasskey2 build
    # ChromeKey was the v1 second key, unused since. The shader now reads it as the ACCENT: the anti-aliased rim of an
    # accent-filled control (the play button) is accent mixed with the surface, and is un-mixed like text is.
    for k, v in vals.items(): subprocess.run(["kwriteconfig6", "--file", "kwinrc", "--group", "Effect-glasskey", "--key", k, str(v)], check=False)
    # the plugin's id is its file name, and a rebuilt plugin is installed under a new one (glasskey1, glasskey2, ...)
    QDBUS = shutil.which("qdbus6") or shutil.which("qdbus-qt6")           # Fedora names it qdbus-qt6; without either, skip the live reconfigure
    loaded = subprocess.run([QDBUS, "org.kde.KWin", "/Effects", "org.kde.kwin.Effects.loadedEffects"], check=False, capture_output=True, text=True).stdout.split() if QDBUS else []
    for name in [n for n in loaded if n.startswith("glasskey")]:
        subprocess.run([QDBUS, "org.kde.KWin", "/Effects", "org.kde.kwin.Effects.reconfigureEffect", name], check=False, capture_output=True)
if "--apply" in sys.argv and shutil.which("spicetify"):
    subprocess.run(["spicetify", "-q", "config", "current_theme", "Glass", "color_scheme", "glass-" + mode], check=False)
    subprocess.run(["spicetify", "-q", "refresh", "-s"], check=False, timeout=30)
print("Glass theme for Spotify written (%s, accent #%s)" % (mode, acc))
